#!/usr/bin/env groovy

def version
def serviceName

pipeline {
    agent any 
	environment {
		dotnet = 'C:\\Program Files (x86)\\dotnet\\'
	}
	
    stages {
	stage('Initialize') {
            steps {
		script {

			version = "${env.GIT_COMMIT[0..6]}-${env.BUILD_NUMBER}"
			serviceName = env.GIT_URL.replaceFirst(/^.*\/([^\/]+?).git$/, '$1')
		}
            }
        }
		
	stage('Checkout'){
            steps {
		script {
			git credentialsId: 'checkoutuser', url: 'https://github.com/mookkaiah/microservice-dotnetcore.git', branch: 'dev'
			}
		}
            }
        }
}

def build(String project){
	sh """
		dotnet publish ${project} -c Release -o ${env.WORKSPACE}/${project}-build
		
		cp ${env.WORKSPACE}/deployment/${project}/* ${env.WORKSPACE}/${project}-build

		mkdir ${env.WORKSPACE}/${project}-build/lib
		
		tar -vczf ${env.WORKSPACE}/${project}.tar.gz -c ${env.WORKSPACE}/${project}-build .
	"""
}
