#!/usr/bin/env groovy
pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Dev-branch- Jenkinsfile practice - Hello world! - triggered by web hooks' 
            }
        }
    }
}