#!/usr/bin/env groovy
pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Jenkinsfile practice - Hello world! - updated' 
            }
        }
    }
}